# Generated by Django 5.0.6 on 2024-07-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0004_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("access_token", models.CharField(max_length=200, unique=True)),
                ("item_id", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="participant_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pilot.pid",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plaid_account_id",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("balances", models.JSONField(null=True)),
                ("mask", models.CharField(max_length=200, null=True)),
                ("name", models.CharField(max_length=200, null=True)),
                ("official_name", models.CharField(max_length=200, null=True)),
                ("subtype", models.CharField(max_length=200, null=True)),
                ("account_type", models.CharField(max_length=200, null=True)),
                (
                    "participant_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pilot.pid",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.plaiditem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.account",
            ),
        ),
    ]
