# Generated by Django 5.0.6 on 2024-07-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_plaiditem_delete_plaidtoken"),
        ("pilot", "0009_alter_pid_participant_id"),
        ("transaction", "0002_plaiditem_transaction_participant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="item",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.plaiditem",
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="plaid_account",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="participant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pilot.pid"
            ),
        ),
        migrations.DeleteModel(
            name="PlaidItem",
        ),
    ]
