# Generated by Django 5.0.6 on 2024-07-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0009_alter_pid_participant_id"),
        (
            "transaction",
            "0003_alter_account_item_remove_transaction_plaid_account_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("access_token", models.CharField(max_length=200, unique=True)),
                ("item_id", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="participant_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pilot.pid",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="item",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.plaiditem",
            ),
        ),
    ]
