# Generated by Django 5.0.6 on 2024-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pending_transaction_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "category_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=500, null=True)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "payment_meta",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "account_owner",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("account_id", models.CharField(blank=True, max_length=500, null=True)),
                ("amount", models.FloatField(default=0)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "unofficial_currency_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=1000, null=True)),
                ("pending", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "authorized_date",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "authorized_datetime",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("datetime", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "transaction_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "check_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "merchant_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "personal_finance_category",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
