# Generated by Django 5.0.7 on 2024-07-30 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "access_token",
                    models.CharField(default="", max_length=64, unique=True),
                ),
                ("item_id", models.CharField(max_length=200, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plaid_account_id",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("balances", models.FloatField(default=0)),
                ("mask", models.CharField(max_length=200, null=True)),
                ("name", models.CharField(max_length=200, null=True)),
                ("official_name", models.CharField(max_length=200, null=True)),
                ("subtype", models.CharField(max_length=200, null=True)),
                ("account_type", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pilot.plaiditem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "pending_transaction_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "category_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "account_owner",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("amount", models.FloatField(default=0)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "unofficial_currency_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=1000, null=True)),
                ("pending", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "original_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "authorized_date",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "authorized_datetime",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("datetime", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "transaction_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "merchant_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "personal_finance_category",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pilot.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
