# Generated by Django 5.0.7 on 2024-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaiditem",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="plaid_account_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
