# Generated by Django 5.0.6 on 2024-06-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="check_number",
        ),
    ]
