# Generated by Django 5.0.7 on 2024-07-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0002_remove_transaction_payment_meta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="item_id",
            new_name="item",
        ),
    ]
