# Generated by Django 5.0.6 on 2024-06-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0002_remove_transaction_check_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
