# Generated by Django 5.1.1 on 2025-01-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_plaiditem_created_alter_account_plaid_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_description',
        ),
    ]
