# Generated by Django 5.0.7 on 2024-07-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0003_rename_item_id_account_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plaiditem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
