# Generated by Django 5.0.6 on 2024-07-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pilot", "0003_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="PID",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("participant_id", models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
