# Generated by Django 5.0.6 on 2024-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pid",
            name="participant_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
