# Generated by Django 5.0.6 on 2024-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0008_alter_pid_participant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pid",
            name="participant_id",
            field=models.PositiveSmallIntegerField(default=None, unique=True),
        ),
    ]
