# Generated by Django 5.0.6 on 2024-07-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("pilot", "0009_alter_pid_participant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(default="", max_length=64)),
                ("item_id", models.CharField(max_length=200, unique=True)),
                (
                    "participant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pilot.pid"
                    ),
                ),
            ],
            options={
                "unique_together": {("access_token", "participant_id")},
            },
        ),
        migrations.DeleteModel(
            name="PlaidToken",
        ),
    ]
